/**
 * @author Magdalena Schwarzkopf
 * @author Dominik Münch
 * 
 *
 * @section DESCRIPTION
 * Unit tests for the two-dimensional wave propagation patch.
 **/
#include <catch2/catch.hpp>
#include "../constants.h"
#include "WavePropagation2d.h"
#include "../setups/CircularDamBreak2d/CircularDamBreak2d.h"

TEST_CASE( "Test the 2d wave propagation with circular dam break setup.", "[WaveProp2dCircularDamBreak]" ) {
  /*
   * Test case:
   *
   * Circular dam break in a 2D domain:
   *   - Inner radius: 10m with water height 10m
   *   - Outer region: water height 5m
   *   - Domain: 50x50 cells from -25 to 25 in both directions
   *   - Cell width: 1m (domain size / number of cells)
   *   - Time step scaling: 0.1 (dt/dx)
   *
   * Expected behavior:
   *   - Water should propagate outward from the dam
   *   - Heights in inner region should decrease
   *   - Heights in outer region should increase
   *   - All water heights should remain non-negative
   *   - Simulation should run without errors
   */

  const tsunami_lab::t_idx l_nCells = 50;
  const tsunami_lab::t_real l_domainSize = 50.0;
  const tsunami_lab::t_real l_cellWidth = l_domainSize / l_nCells;
  const tsunami_lab::t_real l_timeStepScaling = 0.01;

  // Create the 2D wave propagation solver with F-wave solver
  tsunami_lab::patches::WavePropagation2d l_waveProp( l_nCells, l_nCells, true );

  // Create the circular dam break setup
  // Inner: height=10, outside: height=5, centered at origin, radius=10
  tsunami_lab::setups::CircularDamBreak2d l_setup( 10.0, 5.0, 0, 0, 0, 0, 0, 0, 10 );

  // Initialize the patch with setup values
  for( tsunami_lab::t_idx l_iy = 0; l_iy < l_nCells; l_iy++ ) {
    for( tsunami_lab::t_idx l_ix = 0; l_ix < l_nCells; l_ix++ ) {
      // Compute cell center coordinates
      // Domain ranges from -25 to 25, so cell centers are at -24.5, -23.5, ..., 24.5
      tsunami_lab::t_real l_x = -l_domainSize / 2.0 + (l_ix + 0.5) * l_cellWidth;
      tsunami_lab::t_real l_y = -l_domainSize / 2.0 + (l_iy + 0.5) * l_cellWidth;

      // Set initial conditions from setup
      l_waveProp.setHeight( l_ix, l_iy, l_setup.getHeight( l_x, l_y ) );
      l_waveProp.setMomentumX( l_ix, l_iy, l_setup.getMomentumX( l_x, l_y ) );
      l_waveProp.setMomentumY( l_ix, l_iy, l_setup.getMomentumY( l_x, l_y ) );
      l_waveProp.setBathymetry( l_ix, l_iy, l_setup.getBathymetry( l_x, l_y ) );
    }
  }

  // Store initial values near the dam interface for verification.
  // These cells are chosen along y ~ 0: one just inside and one just outside radius 10.
  const tsunami_lab::t_idx l_ixInside = 34;
  const tsunami_lab::t_idx l_ixOutside = 35;
  const tsunami_lab::t_idx l_iyMid = l_nCells / 2;

  tsunami_lab::t_real l_heightInsideBefore = l_waveProp.getHeight()[l_iyMid * l_waveProp.getStride() + l_ixInside];
  tsunami_lab::t_real l_heightOutsideBefore = l_waveProp.getHeight()[l_iyMid * l_waveProp.getStride() + l_ixOutside];

  // Run multiple time steps.
  // Ghost cells must be refreshed every step since the patch swaps old/new buffers.
  for( int l_step = 0; l_step < 30; l_step++ ) {
    l_waveProp.setGhostOutflow();
    l_waveProp.timeStep( l_timeStepScaling );
  }

  // Get values after simulation
  tsunami_lab::t_real const * l_heights = l_waveProp.getHeight();
  tsunami_lab::t_real const * l_momX = l_waveProp.getMomentumX();
  tsunami_lab::t_real const * l_momY = l_waveProp.getMomentumY();

  // Verify that simulation ran correctly

  // Check 1: All water heights should be non-negative
  for( tsunami_lab::t_idx l_iy = 0; l_iy < l_nCells; l_iy++ ) {
    for( tsunami_lab::t_idx l_ix = 0; l_ix < l_nCells; l_ix++ ) {
      tsunami_lab::t_idx l_index = l_iy * l_waveProp.getStride() + l_ix;
      REQUIRE( l_heights[l_index] >= -1e-10 ); // Allow small numerical errors
    }
  }

  // Check 2: Height just inside the dam edge should decrease.
  tsunami_lab::t_real l_heightInsideAfter = l_waveProp.getHeight()[l_iyMid * l_waveProp.getStride() + l_ixInside];
  REQUIRE( l_heightInsideAfter < l_heightInsideBefore );

  // Check 3: Height just outside the dam edge should increase.
  tsunami_lab::t_real l_heightOutsideAfter = l_waveProp.getHeight()[l_iyMid * l_waveProp.getStride() + l_ixOutside];
  REQUIRE( l_heightOutsideAfter > l_heightOutsideBefore );

  // Check 4: Inside should still be higher than outside after a short simulation time.
  REQUIRE( l_heightInsideAfter > l_heightOutsideAfter );

  // Check 5: Some momentum should have been generated by the dam break
  bool l_hasMomentum = false;
  for( tsunami_lab::t_idx l_iy = 0; l_iy < l_nCells; l_iy++ ) {
    for( tsunami_lab::t_idx l_ix = 0; l_ix < l_nCells; l_ix++ ) {
      tsunami_lab::t_idx l_index = l_iy * l_waveProp.getStride() + l_ix;
      if( std::abs( l_momX[l_index] ) > 1e-10 || std::abs( l_momY[l_index] ) > 1e-10 ) {
        l_hasMomentum = true;
        break;
      }
    }
    if( l_hasMomentum ) break;
  }
  REQUIRE( l_hasMomentum );
}

