##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
# @section DESCRIPTION
# Continuous integration using GitHub Actions.
##
name: Tsunami Lab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y scons valgrind cppcheck cmake libhdf5-dev libcurl4-openssl-dev zlib1g-dev
          git submodule init
          git submodule update

      - name: Build netCDF-C
        run: |
          cmake -B submodules/netcdf-c/build \
                -S submodules/netcdf-c \
                -DCMAKE_INSTALL_PREFIX=submodules/netcdf-c/install \
                -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON \
                -DBUILD_SHARED_LIBS=ON \
                -DNETCDF_ENABLE_TESTS=OFF
          cmake --build submodules/netcdf-c/build -j$(nproc)
          cmake --install submodules/netcdf-c/build

      - name: Static Code Analysis
        run:
          cppcheck src/ --template=gcc --force --error-exitcode=1

      - name: Sanitize
        run: |
          scons mode=debug+san
          ./build/tests
          ./build/tsunami_lab 100 100 0 100 1 10 1d outflow dam_break_1d 5 0 2 0 50
          scons mode=release+san
          ./build/tests
          ./build/tsunami_lab 100 100 0 100 1 10 2d dam_break_1d 5 0 2 0 50

      - name: Valgrind
        run: |
          scons mode=debug
          valgrind ./build/tests
          valgrind ./build/tsunami_lab 100 100 0 100 1 10 1d outflow dam_break_1d 5 0 2 0 50

      - name: Release
        run: |
          scons
          ./build/tests
          ./build/tsunami_lab 100 100 0 100 1 10 2d dam_break_1d 5 0 2 0 50